// webui/src/components/ab-edit-rule.vue
<script lang="ts" setup>
import type { BangumiRule } from '#/bangumi';

const emit = defineEmits<{
  (e: 'apply', rule: BangumiRule): void;
  (e: 'enable', id: number): void;
  (
    e: 'deleteFile',
    type: 'disable' | 'delete',
    opts: { id: number; deleteFile: boolean }
  ): void;
}>();

const { t } = useMyI18n();

const show = defineModel('show', { default: false });
const rule = defineModel<BangumiRule>('rule', {
  required: true,
});

const { getAll } = useBangumiStore();

const deleteFileDialog = reactive<{
  show: boolean;
  type: 'disable' | 'delete';
}>({
  show: false,
  type: 'disable',
});

const forceCollectDialog = reactive({
  show: false,
});

const loading = reactive({
  collect: false,
  rename: false,
  deleteFileYes: false,
  deleteFileNo: false,
});

watch(show, (val) => {
  if (!val) {
    deleteFileDialog.show = false;
    forceCollectDialog.show = false;
    loading.deleteFileYes = false;
    loading.deleteFileNo = false;
  }
});

function showDeleteFileDialog(type: String) {
  deleteFileDialog.show = true;
  if (type === 'disable' || type === '禁用') {
    deleteFileDialog.type = 'disable';
  } else {
    deleteFileDialog.type = 'delete';
  }
}

function showForceCollectDialog(show: boolean) {
  forceCollectDialog.show = show;
}

const close = () => (show.value = false);

function emitdeleteFile(deleteFile: boolean) {
  emit('deleteFile', deleteFileDialog.type, {
    id: rule.value.id,
    deleteFile,
  });
}

function forceCollect() {
  if (rule.value) {
    useApi(apiDownload.forceCollect, {
      showMessage: true,
      onBeforeExecute() {
        loading.collect = true;
      },
      onSuccess() {
        getAll();
        show.value = false;
      },
      onFinally() {
        loading.collect = false;
      },
    }).execute(rule.value);
  }
}

function emitApply() {
  emit('apply', rule.value);
}

function emitEnable() {
  emit('enable', rule.value.id);
}

function rename() {
  if (rule.value) {
    useApi(apiBangumi.rename, {
      showMessage: true,
      onBeforeExecute() {
        loading.rename = true;
      },
      onSuccess() {
        getAll();
        show.value = false;
      },
      onFinally() {
        loading.rename = false;
      },
    }).execute(rule.value);
  }
}

const popupTitle = computed(() => {
  if (rule.value.deleted) {
    return t('homepage.rule.enable_rule');
  } else {
    return t('homepage.rule.edit_rule');
  }
});

const boxSize = computed(() => {
  if (rule.value.deleted) {
    return 'w-300';
  } else {
    return 'w-380';
  }
});
</script>

<template>
  <ab-popup
    v-model:show="show"
    :title="popupTitle"
    :css="`${boxSize} max-w-90vw`"
  >
    <div v-if="rule.deleted">
      <div>{{ $t('homepage.rule.enable_hit') }}</div>

      <div line my-8></div>

      <div f-cer gap-x-10>
        <ab-button size="small" type="warn" @click="() => emitEnable()">
          {{ $t('homepage.rule.yes_btn') }}
        </ab-button>
        <ab-button size="small" @click="() => close()">
          {{ $t('homepage.rule.no_btn') }}
        </ab-button>
      </div>
    </div>

    <div v-else space-y-12>
      <ab-rule v-model:rule="rule"></ab-rule>

      <div fx-cer justify-between gap-x-10>
        <ab-button size="small" @click="() => showForceCollectDialog(true)">
          {{ $t('homepage.rule.force_collect') }}
        </ab-button>
        <ab-button size="small" :loading="loading.rename" @click="rename">
          {{ $t('homepage.rule.rename') }}
        </ab-button>
        <div fx-cer justify-end gap-x-10>
          <ab-button-multi
            size="small"
            type="warn"
            :selections="[
              t('homepage.rule.delete'),
              t('homepage.rule.disable'),
            ]"
            @click="showDeleteFileDialog"
          />
          <ab-button size="small" @click="emitApply">
            {{ $t('homepage.rule.apply') }}
          </ab-button>
        </div>
      </div>
    </div>

    <ab-popup
      v-model:show="deleteFileDialog.show"
      :title="$t('homepage.rule.delete')"
    >
      <div>{{ $t('homepage.rule.delete_hit') }}</div>
      <div line my-8></div>

      <div f-cer gap-x-10>
        <ab-button
          size="small"
          type="warn"
          :loading="loading.deleteFileYes"
          @click="
            () => {
              loading.deleteFileYes = true;
              emitdeleteFile(true);
            }
          "
        >
          {{ $t('homepage.rule.yes_btn') }}
        </ab-button>
        <ab-button
          size="small"
          :loading="loading.deleteFileNo"
          @click="
            () => {
              loading.deleteFileNo = true;
              emitdeleteFile(false);
            }
          "
        >
          {{ $t('homepage.rule.no_btn') }}
        </ab-button>
      </div>
    </ab-popup>

    <ab-popup
      v-model:show="forceCollectDialog.show"
      :title="$t('homepage.rule.force_collect')"
    >
      <div>{{ $t('homepage.rule.force_collect_hit') }}</div>
      <div line my-8></div>

      <div f-cer gap-x-10>
        <ab-button
          size="small"
          type="warn"
          :loading="loading.collect"
          @click="forceCollect"
        >
          {{ $t('homepage.rule.yes_btn') }}
        </ab-button>
        <ab-button size="small" @click="() => showForceCollectDialog(false)">
          {{ $t('homepage.rule.no_btn') }}
        </ab-button>
      </div>
    </ab-popup>
  </ab-popup>
</template>

// webui/src/components/rule/ab-edit-rule.tsx
import { Button } from '@/components/ui/button';
import { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { apiBangumi } from '@/api/bangumi';
import { apiDownload } from '@/api/download';
import { executeApi } from '@/hooks/use-api';
import { useBangumiStore } from '@/store/bangumi';
import { AbConfirm } from '@/components/common/ab-confirm';
import { AbPopup } from '@/components/common/ab-popup';
import { AbRule } from '@/components/rule/ab-rule';
import { Checkbox } from '@/components/ui/checkbox';
import { Separator } from '@/components/ui/separator';

export function AbEditRule() {
  const { t } = useTranslation();

  const {
    editRule,
    closeEditPopup,
    setEditItem,
    getAll,
    updateRule,
    enableRule,
    ruleManage,
  } = useBangumiStore();

  const [deleteFileDialog, setDeleteFileDialog] = useState<{
    show: boolean;
    type: 'disable' | 'delete';
    deleteFile: boolean;
  }>({ show: false, type: 'disable', deleteFile: false });

  const [forceCollectDialog, setForceCollectDialog] = useState(false);

  const [loading, setLoading] = useState({
    collect: false,
    rename: false,
    deleteFileYes: false,
  });

  const show = editRule.show;
  const rule = editRule.item;

  useEffect(() => {
    if (!show) {
      setDeleteFileDialog({ show: false, type: 'disable', deleteFile: false });
      setForceCollectDialog(false);
      setLoading((l) => ({ ...l, deleteFileYes: false }));
    }
  }, [show]);

  function showDeleteFileDialog(type: 'disable' | 'delete') {
    setDeleteFileDialog({ show: true, type, deleteFile: false });
  }

  function emitdeleteFile() {
    ruleManage(deleteFileDialog.type, rule.id, deleteFileDialog.deleteFile);
  }

  function forceCollect() {
    executeApi(
      apiDownload.forceCollect,
      {
        showMessage: true,
        onBeforeExecute: () => setLoading((l) => ({ ...l, collect: true })),
        onSuccess() {
          getAll();
          closeEditPopup();
        },
        onFinally: () => setLoading((l) => ({ ...l, collect: false })),
      },
      rule,
    );
  }

  function rename() {
    executeApi(
      apiBangumi.rename,
      {
        showMessage: true,
        onBeforeExecute: () => setLoading((l) => ({ ...l, rename: true })),
        onSuccess() {
          getAll();
          closeEditPopup();
        },
        onFinally: () => setLoading((l) => ({ ...l, rename: false })),
      },
      rule,
    );
  }

  return rule.deleted ? (
    <AbConfirm
      show={show}
      onShowChange={(v) => !v && closeEditPopup()}
      title={t('homepage.rule.enable_rule')}
      width="sm"
      onConfirm={() => enableRule(rule.id)}
    >
      {t('homepage.rule.enable_hit')}
    </AbConfirm>
  ) : (
    <AbPopup
      title={t('homepage.rule.edit_rule')}
      show={show}
      onShowChange={(v) => !v && closeEditPopup()}
      width="xl"
      className="shadow-2xl"
    >
      <div>
        <AbRule rule={rule} onChange={setEditItem} />

        <Separator className="my-4" />

        <div className="flex flex-wrap items-center gap-2 sm:justify-between">
          <div className="flex gap-1">
            <Button variant="ghost" onClick={() => setForceCollectDialog(true)}>
              {t('homepage.rule.force_collect')}
            </Button>

            <Button variant="ghost" loading={loading.rename} onClick={rename}>
              {t('homepage.rule.rename')}
            </Button>

            <Button
              variant="ghost"
              onClick={() => showDeleteFileDialog('disable')}
            >
              {t('homepage.rule.disable')}
            </Button>

            <Button
              variant="ghost"
              className="text-destructive"
              onClick={() => showDeleteFileDialog('delete')}
            >
              {t('homepage.rule.delete')}
            </Button>
          </div>

          <Button
            variant="brand"
            className="order-first h-10 w-full sm:order-last sm:h-8 sm:w-auto sm:min-w-20"
            onClick={() => updateRule(rule.id, rule)}
          >
            {t('homepage.rule.apply')}
          </Button>
        </div>
      </div>

      <AbConfirm
        show={deleteFileDialog.show}
        onShowChange={(v) => setDeleteFileDialog((s) => ({ ...s, show: v }))}
        title={
          deleteFileDialog.type === 'disable'
            ? t('homepage.rule.disable_hit')
            : t('homepage.rule.delete_hit')
        }
        confirmType={deleteFileDialog.type === 'delete' ? 'warn' : 'brand'}
        confirmLoading={loading.deleteFileYes}
        onConfirm={() => {
          setLoading((l) => ({ ...l, deleteFileYes: true }));
          emitdeleteFile();
        }}
      >
        <label className="flex w-fit cursor-pointer items-center gap-2 text-sm">
          <Checkbox
            checked={deleteFileDialog.deleteFile}
            onCheckedChange={(deleteFile) =>
              setDeleteFileDialog((s) => ({ ...s, deleteFile }))
            }
          />
          <span>{t('homepage.rule.delete_file')}</span>
        </label>
      </AbConfirm>

      <AbConfirm
        show={forceCollectDialog}
        onShowChange={setForceCollectDialog}
        title={t('homepage.rule.force_collect')}
        width="sm"
        confirmLoading={loading.collect}
        onConfirm={forceCollect}
      >
        {t('homepage.rule.force_collect_hit')}
      </AbConfirm>
    </AbPopup>
  );
}
